config/routes.rb
Fortunki::Application.routes.draw do
resources :fortunes do
  resources :comments
  
end

match "/auth/:provider/callback" => "sessions#create"
match "/signout" => "sessions#destroy", :as => :signout

root :to => 'fortunes#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :fortune
  validates :author, :presence => true
  validates :quotation, :presence => true
end

app/models/fortune.rb
class Fortune < ActiveRecord::Base
  has_many :comments, :dependent => :destroy
  validates :body, :presence => true
  validates_length_of :body, :in => 2..255
  validates_uniqueness_of :body, :case_sensitive => false

  def self.search(search)
  if search
    where('body LIKE ?', "%#{search}%")
  else
    scoped
  end
end

end

app/models/user.rb
class User < ActiveRecord::Base
def self.create_with_omniauth(auth)
  create! do |user|
    user.provider = auth["provider"]
    user.uid = auth["uid"]
    user.name = auth["user_info"]["name"]
  end
end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery

helper_method :current_user

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter do
    @fortune = Fortune.find(params[:fortune_id])
  end

  def create
    @comment = @fortune.comments.build(params[:comment])
    @comment.save
    respond_with(@fortune, @comment, :location => @fortune)
  end

  def destroy
    @comment = @fortune.comments.find(params[:id])
    @comment.destroy
     respond_with(@fortune, @comment, :location => @fortune)
  end

  def edit
    @comment = @fortune.comments.find(params[:id])
  end

  def update
    @comment = @fortune.comments.find(params[:id])
    @comment.update_attributes(params[:comment])
    respond_with(@fortune, @comment, :location => @fortune)
  end
end

app/controllers/fortunes_controller.rb
class FortunesController < ApplicationController
	respond_to :html, :atom, :js

  # GET /fortunes
  # GET /fortunes.xml
  def index
    @fortunes = Fortune.search(params[:search]).order(:author).page(params[:page]).per(2)
    respond_with(@fortunes)
  end

  # GET /fortunes/1
  # GET /fortunes/1.xml
  def show
    @fortune = Fortune.find(params[:id])

    @comment = Comment.new   
    respond_with(@fortune)
  end

  # GET /fortunes/new
  # GET /fortunes/new.xml
  def new
    @fortune = Fortune.new
    respond_with(@fortune)
  end

  # GET /fortunes/1/edit
  def edit
    @fortune = Fortune.find(params[:id])
  end

  # POST /fortunes
  # POST /fortunes.xml
  def create
    @fortune = Fortune.new(params[:fortune])
    @fortune.save
    respond_with(@fortune)
  end

  # PUT /fortunes/1
  # PUT /fortunes/1.xml
  def update
    @fortune = Fortune.find(params[:id])
    @fortune.update_attributes(params[:fortune])
    respond_with(@fortune)
  end

  # DELETE /fortunes/1
  # DELETE /fortunes/1.xml
  def destroy
    @fortune = Fortune.find(params[:id])
    @fortune.destroy
    respond_with(@fortune)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def create
  auth = request.env["omniauth.auth"]
  user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
  session[:user_id] = user.id
  redirect_to root_url, :notice => "Signed in!"
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Signed out!"
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fortunes_helper.rb
module FortunesHelper
end

app/helpers/layout_helper.rb
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  def show_title?
    @show_title
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/comments/_comment.html.erb
<p><i>Autor:</i> <%= comment.author %></p>
<div class="comment"><i>Quotation:</i>
  <%= comment.quotation %>
</div>
<p>
  <%= link_to "Delete", [@fortune, comment], :confirm => t('helpers.data.sure'), :method => :delete %>
  <%= link_to 'Edit', edit_fortune_comment_path(@fortune, comment) %>
</p>

app/views/comments/_form.html.erb
<%= simple_form_for [@fortune, @comment] do |f| %>
  <%= f.input :author, :input_html => {:size => 40} %>
  <%= f.input :quotation, :input_html => {:rows => 4, :cols => 40} %>
  <%= f.button :submit %>
<% end %>

app/views/comments/edit.html.erb
<% title "Editing comment" %>
<%= render :partial => 'form' %>
<p class="links clear">
  <%= link_to 'Show Fortune', @comment.fortune %>
</p>

app/views/comments/new.html.erb
<% title "New comment" %>
<%= render :partial => 'form' %>
<p class="links clear"><%= link_to 'Back', @comment.fortune %></p>

app/views/fortunes/_form.html.erb
<%= simple_form_for [@fortune] do |f| %>
  <%= f.input :body, :as => :text, :input_html => {:rows => 2, :cols => 72}, :label => '' %>
  <%= f.input :author, :input_html => {:size => 15}, :label => 'Author: '%>
  <%= f.button :submit %>
<% end %>

app/views/fortunes/_fortune.html.erb
<div class="fortune">

<p class="author"><%= fortune.author %></p>

 <p class="body"><b><%= fortune.body %></b><p>
  <div class="links">
     <%= link_to "Show", fortune_path(fortune) %> |
     <%= link_to "Edit", edit_fortune_path(fortune) %> |
     <%= link_to 'Destroy', fortune, :confirm => t('helpers.data.sure'), :method => :delete %>
</div>
 
</div>

app/views/fortunes/edit.html.erb
<% title "Editing fortune" %>

<div class="form edit">
  <%= render 'form' %>
  <div class="link">
    <%= link_to 'Show', @fortune %> |
    <%= link_to 'Back', fortunes_path %>
  </div>
</div>

app/views/fortunes/index.html.erb
<div id="fortunes">
  <%= render :partial => 'fortune', :collection => @fortunes %>
</div>

<div class="link">
  <%= link_to 'New Fortune', new_fortune_path %>
</div>

<%= paginate @fortunes %>

app/views/fortunes/new.html.erb
<%= title "New fortune" %>
<%= render :partial => 'form' %>
<p class="clear"><%= link_to 'Back', fortunes_path %></p>

app/views/fortunes/show.html.erb
<% title "Show fortune" %>

<article class="single">
  <div class="attribute">
    <span class="name">Author</span>
    <span class="value"><%= @fortune.author %></span>
  </div>
  <div class="attribute">
    <span class="name">Body</span>
    <span class="value"><%= @fortune.body %></span>
  </div>

<% if @fortune.comments.any? %>
  <h2>Comments</h2>
  <%= render :partial => 'comments/comment', :collection => @fortune.comments %>
<% end %>

<h2>New Comment</h2>
<%= render :partial => 'comments/form' %>

  <div class="link">
    <%= link_to 'Edit', edit_fortune_path(@fortune) %> |
    <%= link_to 'Back', fortunes_path %>
  </div>
</article>

app/views/layouts/application.html.erb
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
<%= auto_discovery_link_tag(:atom, fortunes_path(:atom)) %>
  <meta charset="utf-8">

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/b/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title><%= content_for?(:title) ? yield(:title) : "fortunka" %></title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width,initial-scale=1">

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

  <%= stylesheet_link_tag "application" %>
  
  <!-- More ideas for your <head> here: h5bp.com/d/head-Tips -->

  <!-- All JavaScript at the bottom, except this Modernizr build incl. Respond.js
       Respond is a polyfill for min/max-width media queries. Modernizr enables HTML5 elements & feature detects; 
       for optimal performance, create your own custom Modernizr build: www.modernizr.com/download/ -->
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <header>
	<search>
     <!--<%= content_tag :h1, "fortunka" %>-->
<%= form_tag fortunes_path, :method => :get, :id => "fortunes_search" do %>
   <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
<% end %>
	</search>
  </header>

<div role="main">
<% if current_user %>
  Welcome <%= current_user.name %>!
  <%= link_to "Sign Out", signout_path %>
<% else %>
  <%= link_to "Sign in with Twitter", "/auth/twitter" %>
<% end %>
</div>

  <div role="main">
    <%= content_tag :h1, yield(:title) if show_title? %>
    <%= yield %>
  </div>
<div role="main"> <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "#{name}" %>
<% end %></div>
  <footer>
  </footer>

  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7 ]>
    <script defer src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    <script defer>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
  <![endif]-->

</body>
</html>